package pkg

var TargetRepository = []string{
	"ent/ent",
	"go-gorm/gorm",
	"huandu/go-sqlbuilder",
	"kyleconroy/sqlc",
	"beego/beego",
	"jmoiron/sqlx",
	"jirfag/go-queryset",
	"jschoedt/go-firestorm",
	"Fs02/grimoire",
	"abrahambotros/lore",
	"dadleyy/marlow",
	"gobuffalo/pop",
	"coocood/qbs",
	"go-reform/reform",
	"go-rel/rel",
	"volatiletech/sqlboiler",
	"uptrace/bun",
	"go-pg/pg",
	"go-xorm/xorm",
	"xo/xo",
	"go-gorp/gorp",
}
